# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='caption',
        ),
    ]
